import Randomizer from "../Services/Randomizer";
import FromListGenerator from "./FromListGenerator";

export default class JobGenerator extends FromListGenerator<string> {
  protected List = [
    "Accountant",
    "Actor",
    "Acupuncturist",
    "Animal Trainer",
    "Arborist",
    "Archaeologist",
    "Architect",
    "Archivist",
    "Artist",
    "Assistant",
    "Astronomer",
    "Auctioneer",
    "Baker",
    "Banker",
    "Bartender",
    "Barber",
    "Blacksmith",
    "Bodyguard",
    "Bookkeeper",
    "Bounty Hunter",
    "Brewer",
    "Bricklayer",
    "Builder",
    "Bureaucrat",
    "Butcher",
    "Captain",
    "Caretaker",
    "Carpenter",
    "Cartographer",
    "Chemist",
    "Cleric",
    "Clerk",
    "Cook",
    "Courier",
    "Dancer",
    "Distiller",
    "Diver",
    "Doctor",
    "Dressmaker",
    "Driver",
    "Engineer",
    "Fisher",
    "Florist",
    "Gardener",
    "Gravedigger",
    "Guard",
    "Herbalist",
    "Housekeeper",
    "Innkeeper",
    "Interpreter",
    "Jeweller",
    "Journalist",
    "Judge",
    "Lawyer",
    "Librarian",
    "Locksmith",
    "Lumberjack",
    "Machinist",
    "Magistrate",
    "Mason",
    "Mercenary",
    "Merchant",
    "Midwife",
    "Miner",
    "Musician",
    "Nanny",
    "Nurse",
    "Operative",
    "Politician",
    "Roofer",
    "Sailor",
    "Scientist",
    "Sculptor",
    "Secretary",
    "Servant",
    "Shipwright",
    "Sheriff",
    "Soldier",
    "Surgeon",
    "Tailor",
    "Tattooist",
    "Tax Collector",
    "Teacher",
    "Undertaker",
    "Warden",
    "Writer"
  ];

  constructor(randomizer: Randomizer) {
      super(randomizer);
  }
}
